### ISSUE TITLE
Not found the yaml for install telemetryService

### ISSUE THREAD

**Issue by p-mega** [Edgenesis/shifu.dev#291]
In Chinese docs for telemetry service(https://shifu.dev/zh-Hans/docs/guides/telemetryservice/installtelemetryservice/)
![screenshot-20240229-193053](https://github.com/Edgenesis/shifu.dev/assets/77156159/21105451-5ea2-47d0-bf2c-0b26cd2a4f4b)
Because there is no release version of shifu in gitee, the yaml is non-exists

**Comment by tomqin93** [comment]
Thank you for this issue. I forgot to sync the gitee mirror. It is working now.
